### ISSUE TITLE
fetcherでtimeoutしたときに不正なエラーが発生する

### ISSUE THREAD

**Issue by DuGlaser** [DuGlaser/atc#4]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6d0bce]

goroutine 1 [running]:
github.com/DuGlaser/atc/internal/repository/fetcher.FetchProblems({0x7ffd0342e6e3?, 0x0?})
        /home/duglaser/src/github.com/DuGlaser/atc/internal/repository/fetcher/fetcher.go:109 +0x10e
github.com/DuGlaser/atc/internal/handler.CreateProject({0x7ffd0342e6e3, 0x6}, 0x0?)
        /home/duglaser/src/github.com/DuGlaser/atc/internal/handler/new.go:26 +0x13a
github.com/DuGlaser/atc/cmd.glob..func5(0xc29b80?, {0xc00007d420, 0x1, 0x1?})
        /home/duglaser/src/github.com/DuGlaser/atc/cmd/new.go:17 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc29b80, {0xc00007d400, 0x1, 0x1})
        /home/duglaser/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc29e00)
        /home/duglaser/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/duglaser/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/DuGlaser/atc/cmd.Execute()
        /home/duglaser/src/github.com/DuGlaser/atc/cmd/root.go:26 +0x25
main.main()
        /home/duglaser/src/github.com/DuGlaser/atc/main.go:6 +0x17
exit status 2
```

**Comment by DuGlaser** [comment]
https://github.com/DuGlaser/atc/commit/3570c542457303ceb830f9907596c4fc3cfd1a07
